### ISSUE TITLE
How do I install this into Brackets?

### ISSUE THREAD

**Issue by digideth** [a-bentofreire/bracketstoix#21]
Since you let your domain expires the previous version (https://github.com/apptoix) of this extension quit working.

Help please.

Thank you!

**Comment by a-bentofreire** [comment]
Sorry about that, 
I wasn't aware that moving the user owner would being the extension into an halt.
I will fix it today.

**Comment by a-bentofreire** [comment]
Can you tell me since when the extension stopped working?
Since it's not related apptoix domain nor https://github.com/apptoix.
The files on brackets extension registry hasn't changed in a very long time and this registry keeps a separated copy of the files, which were download correctly even after a change of ownership on github.
Did it stop working after a Brackets update?
Brackets debugger doesn't give much details about it.
Thank you

**Comment by a-bentofreire** [comment]
The problem is fixed. 
It wasn't due any domain expired or changed ownership, but the fact that recent versions of the Brackets Editor changed their API making the extension unusable. 
Given the number of updates of Brackets Editors is low, the extension must had been disabled for quite a while.
