### ISSUE TITLE
BracketstoIX Installation failing from Brackets Extension Manager (Mac)

### ISSUE THREAD

**Issue by vinch00** [a-bentofreire/bracketstoix#29]
Hello,
On Brackets for Mac, the BracketstoIX installation fails from the Brackets Extension Manager. Downloading the .zip and manually installing in the Brackets Extensions window did not work either. See screenshot below.

The extension used to work perfectly on the same MacOS (High Sierra) until Brackets was upgraded.

OS: MacOS High Sierra (10.13.1)
Brackets Version: Release 1.13 build 1.13.0-17696 (release 49d29a8bc)
BracketstoIX Version: 3.6.0

PS: This extension is really great . Nice work.

![image](https://user-images.githubusercontent.com/14366122/49180758-73091e00-f30a-11e8-898b-bd9e2c55393a.png)

**Comment by lkcampbell** [comment]
@a-bentofreire I'm following up on https://github.com/lkcampbell/brackets-indent-guides/issues/42. The repro is, install your extension, then install the Indent Guides extension, and the Indent Guides extension fails.

The console error is:

`file:///Users/lkcampbell/Library/Application%20Support/Brackets/extensions/user/brackets-indent-guides/lib/i18n.js net::ERR_FILE_NOT_FOUND`

This is weird because I don't use a file with the name. I figured it had something to do with language translations, so I tried to install another translated extension, Beautify, and I got the same type of error in the console:

`file:///Users/lkcampbell/Library/Application%20Support/Brackets/extensions/user/brackets-beautify/lib/text.js net::ERR_FILE_NOT_FOUND`

So, there appears to be some problem with installing translated right after your extension is installed. I will keep looking into the problem, but I thought you might want to look into it as well since there are two reproducible conflicts with your extension.

Let me know if you figure anything out and I will do the same, thanks, Lance.

**Comment by a-bentofreire** [comment]
In order to provide any assistance, I will require the same procedure as stated in my previous comment: 

> 
> Hi,
> Since I'm running the same Brackets and BracketstoIX version without problems, but on Linux,
> I would ask you to press F12 inside brackets, to open the developer tools, and go to the console, and check what is the error that cause the problem. Usually, it's a conflict with other extension but it could be something different.
> If it's not, please, write a comment, with a copy & paste of the all the info displayed on developer tools console.
> Thank you

**Comment by a-bentofreire** [comment]
@lkcampbell This issue is probably a different issue, since what this user reported isn't a conflit with another extension.  
Although the version just released, 3.7.1 also fixes another bug but it's not likely to be the cause of a failure to install the extension.

**Comment by lkcampbell** [comment]
@a-bentofreire yes, I understand now and agree with you. I saw the symptom and jumped to the wrong conclusion. Thanks for your quick assistance on the Indent Guides conflict.
